# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-06 22:50
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', help_text='\u0412\u0438\u0445\u0456\u0434\u043d\u0438\u0439 \u043d\u043e\u043c\u0435\u0440 \u0437\u0430\u044f\u0432\u043d\u0438\u043a\u0430 (\u0431\u0435\u0437 \u0434\u0430\u0442\u0438)', max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('contact', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0412\u0430\u0448\u0456 \u041f\u0406\u0411 \u0442\u0430 \u0442\u0435\u043b\u0435\u0444\u043e\u043d \u0434\u043b\u044f \u0437\u0432\u043e\u0440\u043e\u0442\u043d\u044c\u043e\u0433\u043e \u0437\u0432\u044f\u0437\u043a\u0443', max_length=100, verbose_name='* \u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0438')),
                ('text', models.TextField(blank=True, default='', help_text='\u041e\u043f\u0438\u0448\u0456\u0442\u044c \u0441\u0443\u0442\u044c \u0412\u0430\u0448\u043e\u0433\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', verbose_name='\u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
                ('date', models.DateField(auto_now_add=True, help_text='\u0414\u0430\u0442\u0430 \u043f\u043e\u0434\u0430\u043d\u043d\u044f \u0437\u0430\u044f\u0432\u043a\u0438', null=True, verbose_name='* \u0414\u0430\u0442\u0430')),
                ('resolution_comment', models.CharField(blank=True, default='', help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0434\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0443 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044e \u0434\u043e \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u0457', max_length=250, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440 \u0434\u043e \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u0457')),
                ('canceled', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f \u043e\u0442\u0440\u0438\u043c\u0430\u043b\u043e \u0437\u0430\u043f\u0438\u0442 \u043d\u0430 \u0441\u043a\u0430\u0441\u0443\u0432\u0430\u043d\u043d\u044f', verbose_name='\u0421\u043a\u0430\u0441\u043e\u0432\u0430\u043d\u0435')),
                ('done', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f \u0432\u0438\u043a\u043e\u043d\u0430\u043d\u0435 \u0432\u0438\u043a\u043e\u043d\u0430\u0432\u0446\u0435\u043c', verbose_name='\u0412\u0438\u043a\u043e\u043d\u0430\u043d\u0435')),
                ('closed', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u0449\u043e\u0431 \u0437\u0430\u043a\u0440\u0438\u0442\u0438 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', verbose_name='\u0417\u0430\u043a\u0440\u0438\u0442\u0435')),
                ('author', models.ForeignKey(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0430\u0432\u0442\u043e\u0440\u0430, \u044f\u043a\u0449\u043e \u0432\u0456\u043d \u0432\u0456\u0434\u0440\u0456\u0437\u043d\u044f\u0454\u0442\u044c\u0441\u044f \u0432\u0456\u0434 \u043a\u043b\u0456\u0454\u043d\u0442\u0430', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f \u043a\u043b\u0456\u0454\u043d\u0442\u0456\u0432',
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.ImageField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0434\u043e\u0434\u0430\u0442\u043e\u043a \u0434\u043e\u0412\u0430\u0448\u043e\u0433\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', upload_to=app.models.get_app_attach_upload_path, verbose_name='* \u0414\u043e\u0434\u0430\u0442\u043e\u043a')),
                ('app', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u0434\u043e \u044f\u043a\u043e\u0433\u043e \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0446\u0435\u0439 \u0434\u043e\u0434\u0430\u0442\u043e\u043a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Application', verbose_name='* \u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0434\u0430\u0442\u043e\u043a \u0434\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0414\u043e\u0434\u0430\u0442\u043a\u0438 \u0434\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u044c',
            },
        ),
        migrations.CreateModel(
            name='ApplicationControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c, \u0449\u043e\u0431 \u043f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u0438 \u0437\u0430\u043a\u0440\u0438\u0442\u0442\u044f \u0434\u043e\u0432\u0456\u0434\u043a\u0438', verbose_name='\u041f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043e')),
                ('date', models.DateTimeField(auto_now=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u0443 \u0434\u0430\u0442\u0443 \u0432\u0438\u043a\u043e\u043d\u0430\u043d\u043d\u044f', null=True, verbose_name='\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u0430 \u0434\u0430\u0442\u0430')),
                ('application', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u043d\u0430 \u044f\u043a\u0435 \u043f\u043e\u0442\u0440\u0456\u0431\u043d\u043e \u0434\u043e\u0434\u0430\u0442\u0438 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Application', verbose_name='* \u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u0456',
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='\u0414\u0430\u0442\u0430 \u0432\u043d\u0435\u0441\u0435\u043d\u043d\u044f \u0437\u043c\u0456\u043d \u0434\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', verbose_name='* \u0414\u0430\u0442\u0430')),
                ('action', models.TextField(default='', help_text='\u041e\u043f\u0438\u0441 \u0432\u0447\u0438\u043d\u0435\u043d\u043e\u0457 \u0434\u0456\u0457 \u043d\u0430\u0434 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f\u043c', verbose_name='* \u0414\u0456\u044f')),
                ('application', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u0434\u043e \u044f\u043a\u043e\u0433\u043e \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0446\u044f \u0434\u0456\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Application', verbose_name='* \u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
                ('user', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430, \u044f\u043a\u0438\u043c \u0432\u043d\u0435\u0441\u0435\u043d\u0456 \u0437\u043c\u0456\u043d\u0438', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='* \u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447')),
            ],
            options={
                'verbose_name': '\u0417\u043c\u0456\u043d\u0430 \u043d\u0430\u0434 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f\u043c',
                'verbose_name_plural': '\u0406\u0441\u0442\u043e\u0440\u0456\u044f \u0437\u043c\u0456\u043d \u043d\u0430\u0434 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f\u043c\u0438',
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', help_text='\u0412\u0432\u0435\u0434\u0456\u0442\u044c \u0442\u0435\u043a\u0441\u0442 \u0412\u0430\u0448\u043e\u0433\u043e \u043f\u043e\u0432\u0456\u0434\u043e\u043c\u043b\u0435\u043d\u043d\u044f', verbose_name='* \u041f\u043e\u0432\u0456\u0434\u043e\u043c\u043b\u0435\u043d\u043d\u044f')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u0449\u043e \u044f\u043a\u043e\u0433\u043e \u0431\u0443\u0434\u0435 \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u0438\u0441\u044c \u0446\u0435 \u043f\u043e\u0432\u0456\u0434\u043e\u043c\u043b\u0435\u043d\u043d\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Application', verbose_name='* \u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
                ('user', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430 - \u0430\u0432\u0442\u043e\u0440\u0430 \u043f\u043e\u0432\u0456\u0434\u043e\u043c\u043b\u0435\u043d\u043d\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='* \u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0432\u0456\u0434\u043e\u043c\u043b\u0435\u043d\u043d\u044f \u0434\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u041f\u0435\u0440\u0435\u043f\u0438\u0441\u043a\u0430 \u043f\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044e',
            },
        ),
        migrations.CreateModel(
            name='ApplicationScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.ImageField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0441\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u044e \u0412\u0430\u0448\u043e\u0433\u043e \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', upload_to=app.models.get_app_scan_upload_path, verbose_name='* \u0421\u043a\u0430\u043d')),
                ('app', models.ForeignKey(default=None, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u0434\u043e \u044f\u043a\u043e\u0433\u043e \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0446\u044f \u0441\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Application', verbose_name='* \u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u044f \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0421\u043a\u0430\u043d\u043e\u0432\u0430\u043d\u0456 \u043a\u043e\u043f\u0456\u0457 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u044c',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430 \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u0437\u0430\u044f\u0432\u043a\u0438', max_length=50, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
                ('type', models.CharField(choices=[('initial', '\u041f\u043e\u0447\u0430\u0442\u043a\u043e\u0432\u0438\u0439'), ('interim', '\u041f\u0440\u043e\u043c\u0456\u0436\u043d\u0438\u0439'), ('quits', '\u0417\u0430\u0432\u0435\u0440\u0448\u0430\u043b\u044c\u043d\u0438\u0439')], default='interim', help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440 \u0441\u0442\u0430\u0442\u0443\u0441\u0443. \u041f\u0440\u0438\u043c\u0456\u0442\u043a\u0430: \u0434\u043b\u044f \u043a\u043e\u0440\u0435\u043a\u0442\u043d\u043e\u0441\u0442\u0456 \u0440\u043e\u0431\u043e\u0442\u0438 \u043f\u043e\u0447\u0430\u0442\u043a\u043e\u0432\u0438\u0439 \u0441\u0442\u0430\u0442\u0443\u0441 \u043f\u043e\u0432\u0438\u043d\u0435\u043d \u0431\u0443\u0442\u0438 \u043b\u0438\u0448\u0435 \u043e\u0434\u0438\u043d. \u0412\u0456\u043d \u0431\u0443\u0434\u0435 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u043e \u043f\u0440\u0438\u0437\u043d\u0430\u0447\u0430\u0442\u0438\u0441\u044f \u043d\u0430 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u0449\u043e \u043e\u0442\u0440\u0438\u043c\u0430\u043b\u0438 \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u044e.', max_length=7, verbose_name='* \u0422\u0438\u043f \u0441\u0442\u0430\u0442\u0443\u0441\u0443')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u0438 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043d\u0430\u0437\u0432\u0443 \u0444\u043e\u0440\u043c\u0438 \u0437\u0430\u044f\u0432\u043a\u0438', max_length=50, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
                ('form_template', models.CharField(choices=[('about.html', 'about'), ('about.html.py', 'about.py'), ('contact.html', 'contact'), ('contact.html.py', 'contact.py'), ('index.html', 'index'), ('index.html.py', 'index.py'), ('layout.html', 'layout'), ('layout.html.py', 'layout.py')], help_text='\u041e\u0431\u0435\u0440\u0456\u0442\u044c \u0448\u0430\u0431\u043b\u043e\u043d \u0437\u0430\u044f\u0432\u043a\u0438 \u0437 \u043d\u0430\u044f\u0432\u043d\u0438\u0445 (\u043f\u0456\u0434\u0433\u043e\u0442\u043e\u0432\u043b\u0435\u043d\u0438\u0439 html \u0444\u0430\u0439\u043b)', max_length=50, verbose_name='* \u0424\u043e\u0440\u043c\u0430 \u0448\u0430\u0431\u043b\u043e\u043d\u0443')),
                ('deprecated', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0444\u043e\u0440\u043c\u0430 \u043d\u0435\u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u0430', verbose_name='\u0417\u0430\u0441\u0442\u0430\u0440\u0456\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0422\u0438\u043f\u0438 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u041d\u0430\u0437\u0432\u0430 \u043a\u043b\u0456\u0454\u043d\u0442\u0430', max_length=250, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
                ('full_name', models.CharField(blank=True, default='', help_text='\u041f\u043e\u0432\u043d\u0430 \u043d\u0430\u0437\u0432\u0430 \u043a\u043b\u0456\u0454\u043d\u0442\u0430', max_length=250, verbose_name='\u041f\u043e\u0432\u043d\u0430 \u043d\u0430\u0437\u0432\u0430')),
                ('balance', models.IntegerField(blank=True, default=0, help_text='\u041f\u043e\u0442\u043e\u0447\u043d\u0438\u0439 \u0441\u0430\u043b\u044c\u0434\u043e\u0432\u0438\u0439 \u0431\u0430\u043b\u0430\u043d\u0441', verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441')),
                ('avatar', models.ImageField(blank=True, default='/media/default-profile.jpg', help_text='\u0417\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0442\u0435 \u0412\u0430\u0448\u0435 \u0444\u043e\u0442\u043e', upload_to=app.models.get_client_avatar_upload_path, verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440')),
                ('address', models.CharField(blank=True, default='', help_text='\u0424\u0430\u043a\u0442\u0438\u0447\u043d\u0430 \u0430\u0434\u0440\u0435\u0441\u0430 \u043a\u043b\u0456\u0454\u043d\u0442\u0430', max_length=100, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430')),
                ('phone', models.CharField(blank=True, default='', help_text='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0438\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d. \u041c\u0430\u043a\u0441\u0438\u043c\u0443\u043c 20 \u0446\u0438\u0444\u0440', max_length=20, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('fop', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0446\u0435 \u0444\u0456\u0437\u0438\u0447\u043d\u0430 \u043e\u0441\u043e\u0431\u0430 \u043f\u0456\u0434\u043f\u0440\u0438\u0454\u043c\u0435\u0446\u044c', verbose_name='\u0424\u041e\u041f')),
                ('code_ipn', models.CharField(blank=True, default='', help_text='\u041a\u043e\u0434 \u0404\u0414\u0420\u041f\u041e\u0423/\u0414\u0420\u0424\u041e. \u041c\u0430\u043a\u0441\u0438\u043c\u0443\u043c 12 \u0446\u0438\u0444\u0440', max_length=12, verbose_name='\u0404\u0414\u0420\u041f\u041e\u0423/\u0414\u0420\u0424\u041e')),
                ('code_1c', models.CharField(blank=True, default='', help_text='\u0412\u0432\u0435\u0434\u0456\u0442\u044c \u0432\u043d\u0443\u0442\u0440\u0456\u0448\u043d\u0456\u0439 \u043a\u043e\u0434 1\u0441. \u041c\u0430\u043a\u0441\u0438\u043c\u0443\u043c 9 \u0446\u0438\u0444\u0440', max_length=9, verbose_name='\u041a\u043e\u0434 1\u0441')),
                ('email_verified', models.BooleanField(default=False, help_text='\u0427\u0438 \u0432\u0435\u0440\u0438\u0444\u0456\u043a\u0430\u0432\u0430\u043d\u0438\u0439 email', verbose_name='Email \u043f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043e')),
                ('init_date', models.DateField(auto_now_add=True, help_text='\u0414\u0430\u0442\u0430 \u0441\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f', null=True, verbose_name='* \u0414\u0430\u0442\u0430')),
                ('deprecated', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u0449\u043e\u0431 \u0434\u0435\u0430\u043a\u0442\u0438\u0432\u0443\u0432\u0430\u0442\u0438 \u043a\u043b\u0456\u0454\u043d\u0442\u0430', verbose_name='\u041d\u0435\u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u0456\u0454\u043d\u0442',
                'verbose_name_plural': '\u041a\u043b\u0456\u0454\u043d\u0442\u0438',
                'permissions': (('client_role', 'User has client rights'),),
            },
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043d\u0430\u0437\u0432\u0443 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u0457', max_length=50, verbose_name='* \u041d\u0430\u0437\u0432\u0430 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u0457')),
                ('description', models.CharField(blank=True, default='', help_text='\u041e\u043f\u0438\u0441 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u0457', max_length=100, verbose_name='\u041e\u043f\u0438\u0441')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='\u0412\u0456\u0434\u0441\u043e\u0442\u043e\u043a \u0437\u043d\u0438\u0436\u043a\u0438', verbose_name='\u0417\u043d\u0438\u0436\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f \u043a\u043b\u0456\u0454\u043d\u0442\u0430',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u0457 \u043a\u043b\u0456\u0454\u043d\u0442\u0456\u0432',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043d\u0430\u0437\u0432\u0443 \u0432\u0456\u0434\u0434\u0456\u043b\u0443', max_length=30, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u0412\u0456\u0434\u0434\u0456\u043b',
                'verbose_name_plural': '\u0412\u0456\u0434\u0434\u0456\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='DepartmentEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0456\u0434\u0434\u0456\u043b \u0434\u043e \u044f\u043a\u043e\u0433\u043e \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c \u0446\u0435\u0439 \u043f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department', verbose_name='* \u0412\u0456\u0434\u0434\u0456\u043b')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a \u0432\u0456\u0434\u0434\u0456\u043b\u0443',
                'verbose_name_plural': '\u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a\u0438 \u043f\u043e \u0432\u0456\u0434\u0434\u0456\u043b\u0430\u043c',
            },
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0456\u0434\u0434\u0456\u043b, \u044f\u043a\u043e\u043c\u0443 \u0431\u0443\u0434\u0435 \u043f\u0440\u0438\u0437\u043d\u0430\u0447\u0435\u043d\u043e \u043a\u0435\u0440\u0456\u0432\u043d\u0438\u043a\u0430', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department', verbose_name='* \u0412\u0456\u0434\u0434\u0456\u043b')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0447\u0430\u043b\u044c\u043d\u0438\u043a \u0432\u0456\u0434\u0434\u0456\u043b\u0443',
                'verbose_name_plural': '\u041d\u0430\u0447\u0430\u043b\u044c\u043d\u0438\u043a\u0438 \u0432\u0456\u0434\u0434\u0456\u043b\u0456\u0432',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='/media/default-profile.jpg', help_text='\u0417\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0442\u0435 \u0441\u0432\u043e\u0454 \u0444\u043e\u0442\u043e', max_length=250, upload_to=app.models.get_employee_avatar_upload_path, verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440')),
                ('email_verified', models.BooleanField(default=False, help_text='\u0427\u0438 \u0432\u0435\u0440\u0438\u0444\u0456\u043a\u0430\u0432\u0430\u043d\u0438\u0439 email', verbose_name='Email \u043f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043e')),
                ('deprecated', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u0449\u043e\u0431 \u0434\u0435\u0430\u043a\u0442\u0438\u0432\u0443\u0432\u0430\u0442\u0438 \u043f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a\u0430', verbose_name='\u041d\u0435\u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u0438\u0439')),
                ('user', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u043d\u043e\u0433\u043e \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='* \u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a',
                'verbose_name_plural': '\u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a\u0438',
                'permissions': (('employee_role', 'User has employee rights'), ('department_head_role', 'User has rights of department head'), ('secretary_role', 'User has secretary rights'), ('manager_role', 'User has rights of manager'), ('moderator_role', 'User has moderator rights')),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043d\u0430\u0437\u0432\u0443 \u043a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u043e\u0457 \u043c\u0456\u0442\u043a\u0438', max_length=50, verbose_name='* \u041d\u0430\u0437\u0432\u0430 \u043c\u0456\u0442\u043a\u0438')),
                ('color', models.CharField(default='ffffff', help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u043e\u043b\u0456\u0440, \u0449\u043e \u0431\u0443\u0434\u0435 \u0432\u0438\u043a\u043e\u0440\u0438\u0441\u0442\u043e\u0432\u0443\u0432\u0430\u0442\u0438\u0441\u044f \u0434\u043b\u044f \u0446\u0456\u0454\u0457 \u043c\u0456\u0442\u043a\u0438\u041a\u043e\u0434 \u043a\u043e\u043b\u044c\u043e\u0440\u0443 \u0443 HEX \u0444\u043e\u0440\u043c\u0430\u0442\u0456 (6 \u0446\u0438\u0444\u0440)', max_length=6, verbose_name='* \u041a\u043e\u043b\u0456\u0440')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u0430 \u043c\u0456\u0442\u043a\u0430',
                'verbose_name_plural': '\u041a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u0456 \u043c\u0456\u0442\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043d\u0430\u0437\u0432\u0443 \u043e\u0446\u0456\u043d\u043a\u0438', max_length=30, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
                ('absolute', models.IntegerField(default=0, help_text='\u0410\u0431\u0441\u043e\u043b\u044e\u0442\u043d\u0435 \u0447\u0438\u0441\u043b\u043e\u0432\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u043d\u044f, \u0449\u043e \u0431\u0443\u0434\u0435 \u0432\u0438\u043a\u043e\u0440\u0438\u0441\u0442\u043e\u0432\u0443\u0432\u0430\u0442\u0438\u0441\u044f\u0434\u043b\u044f \u043f\u043e\u0440\u0456\u0432\u043d\u044f\u043d\u043d\u044f. \u0427\u0438\u043c \u0431\u0456\u043b\u044c\u0448\u0435 \u0430\u0431\u0441\u043e\u043b\u044e\u0442\u043d\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u043d\u044f - \u0442\u0438\u043c \u043a\u0440\u0430\u0449\u0430 \u043e\u0446\u0456\u043d\u043a\u0430', verbose_name='* \u0410\u0431\u0441\u043e\u043b\u044e\u0442\u043d\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u043d\u044f')),
                ('picture', models.ImageField(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0443, \u0449\u043e \u0431\u0443\u0434\u0435 \u0430\u0441\u043e\u0446\u0456\u0439\u043e\u0432\u0430\u043d\u0430 \u0437 \u0446\u0456\u0454\u044e \u043e\u0446\u0456\u043d\u043a\u043e\u044e', null=True, upload_to=app.models.get_mark_upload_path, verbose_name='* \u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0446\u0456\u043d\u043a\u0430',
                'verbose_name_plural': '\u041e\u0446\u0456\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0442\u0435\u043a\u0441\u0442 \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u0457', max_length=50, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
                ('quits', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0434\u0430\u043d\u0430 \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u044f \u043e\u0437\u043d\u0430\u0447\u0430\u0454 \u0432\u0456\u0434\u0445\u0438\u043b\u0435\u043d\u043d\u044f / \u0437\u0430\u043a\u0440\u0438\u0442\u0442\u044f \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', verbose_name='\u041e\u0437\u043d\u0430\u043a\u0430 \u0432\u0456\u0434\u0445\u0438\u043b\u0435\u043d\u043d\u044f')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u044f',
                'verbose_name_plural': '\u0412\u0438\u0434\u0438 \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u0439',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', help_text='\u0412\u0438\u0445\u0456\u0434\u043d\u0438\u0439 \u0432\u043d\u0443\u0442\u0440\u0456\u0448\u043d\u0456\u0439\u043d\u043e\u043c\u0435\u0440 (\u0431\u0435\u0437 \u0434\u0430\u0442\u0438)', max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('title', models.CharField(blank=True, default='', help_text='\u0422\u0435\u043a\u0441\u0442 \u0448\u0430\u043f\u043a\u0438 \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456 (\u043a\u043e\u043c\u0443)', max_length=100, verbose_name='\u0428\u0430\u043f\u043a\u0430')),
                ('text', models.TextField(blank=True, default='', help_text='\u0422\u0435\u043a\u0441\u0442 \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456', verbose_name='\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c')),
                ('date', models.DateField(auto_now_add=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0434\u0430\u0442\u0443 \u043d\u0430\u0434\u0430\u043d\u043d\u044f \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456', verbose_name='\u0414\u0430\u0442\u0430')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0430\u0440\u0442\u0456\u0441\u0442\u044c \u043d\u0430\u0434\u0430\u043d\u0438\u0445 \u043f\u043e\u0441\u043b\u0443\u0433', max_digits=6, verbose_name='\u0412\u0430\u0440\u0442\u0456\u0441\u0442\u044c')),
                ('client_review', models.TextField(blank=True, default='', help_text='\u0412\u0456\u0434\u0433\u0443\u043a \u043a\u043b\u0456\u0454\u043d\u0442\u0430', max_length=254, verbose_name='\u0412\u0456\u0434\u0433\u0443\u043a')),
                ('application', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f, \u0434\u043e \u044f\u043a\u043e\u0433\u043e\u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c \u0446\u044f \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Application', verbose_name='* \u0417\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f')),
                ('client_mark', models.ForeignKey(help_text='\u041e\u0446\u0456\u043d\u043a\u0430 \u043a\u043b\u0456\u0454\u043d\u0442\u0430', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Mark', verbose_name='\u041e\u0446\u0456\u043d\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c',
                'verbose_name_plural': '\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456',
            },
        ),
        migrations.CreateModel(
            name='ResponseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.ImageField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0435\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0443 \u043a\u043e\u043f\u0456\u044e \u0434\u043e\u0434\u0430\u0442\u043a\u0443', upload_to=app.models.get_resp_attach_upload_path, verbose_name='* \u0414\u043e\u0434\u0430\u0442\u043e\u043a')),
                ('response', models.ForeignKey(help_text='\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c, \u0434\u043e \u044f\u043a\u043e\u0457 \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0446\u0435\u0439 \u0434\u043e\u0434\u0430\u0442\u043e\u043a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Response', verbose_name='* \u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u044f \u0434\u043e\u0434\u0430\u0442\u043a\u0443 \u0434\u043e \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456',
                'verbose_name_plural': '\u0421\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u0457 \u0434\u043e\u0434\u0430\u0442\u043a\u0456\u0432 \u0434\u043e \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456',
            },
        ),
        migrations.CreateModel(
            name='ResponseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ImageField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0435\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0443 \u043a\u043e\u043f\u0456\u044e \u0440\u0430\u0445\u0443\u043d\u043a\u0443', upload_to=app.models.get_resp_bill_upload_path, verbose_name='* \u0420\u0430\u0445\u0443\u043d\u043e\u043a')),
                ('response', models.ForeignKey(help_text='\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c, \u0434\u043e \u044f\u043a\u043e\u0457 \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0446\u0435\u0439 \u0440\u0430\u0445\u0443\u043d\u043e\u043a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Response', verbose_name='* \u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c')),
            ],
            options={
                'verbose_name': '\u0415\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0438\u0439 \u0440\u0430\u0445\u0443\u043d\u043e\u043a',
                'verbose_name_plural': '\u0415\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0456 \u0440\u0430\u0445\u0443\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='ResponsePerformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Employee', verbose_name='')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Response', verbose_name='')),
            ],
            options={
                'verbose_name': '\u0412\u0438\u043a\u043e\u043d\u0430\u0432\u0435\u0446\u044c \u0437\u0430\u043c\u043e\u0432\u043b\u0435\u043d\u043d\u044f',
                'verbose_name_plural': '\u0412\u0438\u043a\u043e\u043d\u0430\u0432\u0446\u0456 \u0437\u0430\u043c\u043e\u0432\u043b\u0435\u043d\u043d\u044f',
            },
        ),
        migrations.CreateModel(
            name='ResponseScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.ImageField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0435\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0443 \u043a\u043e\u043f\u0456\u044e \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456', upload_to=app.models.get_resp_scan_upload_path, verbose_name='* \u0421\u043a\u0430\u043d')),
                ('response', models.ForeignKey(help_text='\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c, \u0434\u043e \u044f\u043a\u043e\u0457 \u0432\u0456\u0434\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0446\u0435\u0439 \u0441\u043a\u0430\u043d', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Response', verbose_name='* \u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u044f \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456',
                'verbose_name_plural': '\u0421\u043a\u0430\u043d \u043a\u043e\u043f\u0456\u0457 \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043d\u0430\u0437\u0432\u0443 \u0444\u043e\u0440\u043c\u0438 \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456', max_length=50, verbose_name='* \u041d\u0430\u0437\u0432\u0430')),
                ('form_template', models.CharField(choices=[('index.html', 'index'), ('index.html.py', 'index.py'), ('layout.html', 'layout'), ('layout.html.py', 'layout.py')], help_text='\u041e\u0431\u0435\u0440\u0456\u0442\u044c \u0448\u0430\u0431\u043b\u043e\u043d \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456 \u0437 \u043d\u0430\u044f\u0432\u043d\u0438\u0445(\u043f\u0456\u0434\u0433\u043e\u0442\u043e\u0432\u043b\u0435\u043d\u0438\u0439 html \u0444\u0430\u0439\u043b)', max_length=50, verbose_name='* \u0424\u043e\u0440\u043c\u0430 \u0448\u0430\u0431\u043b\u043e\u043d\u0443')),
                ('deprecated', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0444\u043e\u0440\u043c\u0430 \u043d\u0435\u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u0430', verbose_name='\u0417\u0430\u0441\u0442\u0430\u0440\u0456\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456',
                'verbose_name_plural': '\u0422\u0438\u043f\u0438 \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='\u0422\u0435\u043a\u0441\u0442 \u0432\u0456\u0434\u0433\u0443\u043a\u0443', max_length=1000, verbose_name='* \u0412\u0456\u0434\u0433\u0443\u043a')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='\u0414\u0430\u0442\u0430 \u043d\u0430\u043f\u0438\u0441\u0430\u043d\u043d\u044f \u0432\u0456\u0434\u0433\u0443\u043a\u0443', verbose_name='* \u0414\u0430\u0442\u0430')),
                ('anonymously', models.BooleanField(default=False, help_text='\u0427\u0438 \u043e\u043f\u0443\u0431\u043b\u0456\u043a\u043e\u0432\u0430\u043d\u043e \u0430\u043d\u043e\u043d\u0456\u043c\u043d\u043e', verbose_name='\u0410\u043d\u043e\u043d\u0456\u043c\u043d\u043e')),
                ('approved', models.BooleanField(default=False, help_text='\u0412\u0456\u0434\u043c\u0456\u0442\u044c\u0442\u0435, \u044f\u043a\u0449\u043e \u0432\u0456\u0434\u0433\u0443\u043a \u043f\u0440\u043e\u0439\u0448\u043e\u0432 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0456\u044e', verbose_name='\u041f\u043e\u0433\u043e\u0434\u0436\u0435\u043d\u043e')),
                ('client', models.ForeignKey(help_text='\u041a\u043b\u0456\u0454\u043d\u0442, \u0449\u043e \u0437\u0430\u043b\u0438\u0448\u0438\u0432 \u0432\u0456\u0434\u0433\u0443\u043a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Client', verbose_name='* \u041a\u043b\u0456\u0454\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0412\u0456\u0434\u0433\u0443\u043a',
                'verbose_name_plural': '\u0412\u0456\u0434\u0433\u0443\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_department', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0456\u0434\u0434\u0456\u043b, \u0449\u043e \u043f\u0456\u0434\u043f\u043e\u0440\u044f\u0434\u043a\u043e\u0432\u0443\u0454\u0442\u044c\u0441\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_department', to='app.Department', verbose_name='* \u041f\u0456\u0434\u043f\u043e\u0440\u044f\u0434\u043a\u0443\u0432\u0430\u043d\u043d\u044f')),
                ('parent_department', models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0456\u0434\u0434\u0456\u043b, \u0449\u043e \u0454 \u0433\u043e\u043b\u043e\u0432\u043d\u0438\u043c', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_department', to='app.Department', verbose_name='* \u0413\u043e\u043b\u043e\u0432\u043d\u0438\u0439 \u0432\u0456\u0434\u0434\u0456\u043b')),
            ],
            options={
                'verbose_name': '\u041f\u0456\u0434\u043f\u043e\u0440\u044f\u0434\u043a\u0443\u0432\u0430\u043d\u043d\u044f \u0432\u0456\u0434\u0434\u0456\u043b\u0443',
                'verbose_name_plural': '\u041f\u0456\u0434\u043f\u043e\u0440\u044f\u0434\u043a\u0443\u0432\u0430\u043d\u043d\u044f \u0432\u0456\u0434\u0434\u0456\u043b\u0456\u0432',
            },
        ),
        migrations.AddField(
            model_name='response',
            name='type',
            field=models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0442\u0438\u043f \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u0456', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ResponseType', verbose_name='* \u0422\u0438\u043f'),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='employee',
            field=models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u0435\u0440\u0456\u0432\u043d\u0438\u043a\u0430 \u0432\u0456\u0434\u0434\u0456\u043b\u0443', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Employee', verbose_name='* \u041a\u0435\u0440\u0456\u0432\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='employee',
            field=models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a\u0430 \u0432\u0456\u0434\u0434\u0456\u043b\u0443', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Employee', verbose_name='* \u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='clientcategory',
            name='label',
            field=models.ForeignKey(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u0443 \u043c\u0456\u0442\u043a\u0443 \u0434\u043b\u044f \u0433\u0440\u0443\u043f\u0438.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Label', verbose_name='\u041a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u0430 \u043c\u0456\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044e \u043a\u043b\u0456\u0454\u043d\u0442\u0430', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ClientCategory', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f \u043a\u043b\u0456\u0454\u043d\u0442\u0456\u0432'),
        ),
        migrations.AddField(
            model_name='client',
            name='overall_mark',
            field=models.ForeignKey(blank=True, help_text='\u0417\u0430\u0433\u0430\u043b\u044c\u043d\u0430 \u043e\u0446\u0456\u043d\u043a\u0430 \u0434\u0456\u044f\u043b\u044c\u043d\u043e\u0441\u0442\u0456 \u043e\u0440\u0433\u0430\u043d\u0456\u0437\u0430\u0446\u0456\u0457', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Mark', verbose_name='\u0417\u0430\u0433\u0430\u043b\u044c\u043d\u0430 \u043e\u0446\u0456\u043d\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(help_text='\u0412\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u043d\u0438\u0439 \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='* \u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='label',
            field=models.ForeignKey(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u0443 \u043c\u0456\u0442\u043a\u0443,\u0449\u043e \u0431\u0443\u0434\u0435 \u0430\u0441\u043e\u0446\u0456\u044e\u0432\u0430\u0442\u0438\u0441\u044f \u0437 \u0446\u0438\u043c \u0441\u0442\u0430\u0442\u0443\u0441\u043e\u043c', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Label', verbose_name='\u041a\u043e\u043b\u044c\u043e\u0440\u043e\u0432\u0430 \u043c\u0456\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='applicationcontrol',
            name='employee',
            field=models.ForeignKey(help_text='\u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a, \u0449\u043e \u0431\u0430\u0436\u0430\u0454 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044e\u0432\u0430\u0442\u0438 \u0437\u0430\u043a\u0440\u0438\u0442\u0442\u044f \u0434\u043e\u0432\u0456\u0434\u043a\u0438', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Employee', verbose_name='* \u041f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0432\u0456\u0434\u043f\u043e\u0432\u0456\u0434\u043d\u043e\u0433\u043e \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430', on_delete=django.db.models.deletion.PROTECT, to='app.Client', verbose_name='* \u041a\u043b\u0456\u0454\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='application',
            name='resolution',
            field=models.ForeignKey(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u0440\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u044e \u043d\u0430 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Resolution', verbose_name='\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0456\u044f'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, help_text='\u0412\u043a\u0430\u0436\u0456\u0442\u044c \u043f\u043e\u0442\u043e\u0447\u043d\u0438\u0439 \u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ApplicationStatus', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.ForeignKey(help_text='\u041e\u0431\u0435\u0440\u0456\u0442\u044c \u043c\u043e\u0436\u043b\u0438\u0432\u0443 \u043f\u0440\u0438\u0447\u0438\u043d\u0443 \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f', on_delete=django.db.models.deletion.PROTECT, to='app.ApplicationType', verbose_name='* \u0422\u0438\u043f \u0437\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f'),
        ),
    ]
