# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161108_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('employee_role', 'User has employee rights'), ('moderator_role', 'User has moderator rights'), ('department_head_role', 'User has rights of department head'), ('secretary_role', 'User has secretary rights'), ('manager_role', 'User has rights of manager')), 'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.AlterField(
            model_name='application',
            name='contact',
            field=models.TextField(help_text='Вкажіть Ваші ПІБ та телефон для зворотнього звязку', verbose_name='* Контакти'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='form_template',
            field=models.CharField(choices=[('general.html', 'general'), ('source-sertificate.html', 'source-sertificate'), ('price-inquiry.html', 'price-inquiry')], help_text='Оберіть шаблон заявки з наявних (підготовлений html файл)', max_length=50, verbose_name='* Форма шаблону'),
        ),
    ]
